### ISSUE TITLE
1.13 update.

### ISSUE THREAD

**Issue by mibby** [Esophose/PlayerParticles#10]
https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-13-pre7-development-builds.328883/

Spigot 1.13 pre-release builds have finally arrived. Perhaps you might want to take a look at the particle name changes and removals to prepare for PlayerParticles 1.13 support. :)

**Comment by Esophose** [comment]
Thanks for the notice, I'll start working on it then.
