### ISSUE TITLE
Command to fully remove all effects and styles both at once.

### ISSUE THREAD

**Issue by mibby** [Esophose/PlayerParticles#12]
Since the styles and effects GUI are now sorted alphabetically, I've had users complain that the option to disable particles no longer exists. It use to be in the top left, now somewhere down in the middle of each gui section.

Would it be possible to implement a single command to fully remove your particle so players could ```/pp none``` for example instead of having to find the option on each section or type ```/pp particle none``` & ```/pp style none```? Alternatively, what about an option on the main PP GUI page to remove your particle below the 3 available options?

**Comment by Esophose** [comment]
You're in luck! The command /pp reset already exists. I'll probably move the clear options to the bottom left corner of the GUIs in the next update, they are kind of difficult to find now.

**Comment by mibby** [comment]
I never knew about that command! That helps a lot. Though having the clear options in a visible spot for players to see in the GUI would also definitely help. Thanks!

**Comment by Esophose** [comment]
If you ever want to know all the available commands, you can type /pp help.
