### ISSUE TITLE
Spigot 1.8.8 [Error]

### ISSUE THREAD

**Issue by Vejksu42** [Esophose/PlayerParticles#13]
PlayerParticles v5.2
![default](https://user-images.githubusercontent.com/44622590/47751147-12061000-dca2-11e8-9a62-3a163ea92cf8.PNG)

**Comment by Esophose** [comment]
PlayerParticles v5.2 is not compatible with Minecraft 1.8.8. Please use PlayerParticles v5 -- Bukkit 1.8 instead.
