### ISSUE TITLE
French language and 6.3

### ISSUE THREAD

**Issue by aurel85** [Esophose/PlayerParticles#16]
Hi,

With 6.3 the accents of the french language (é, è, ê...) do not display correctly contrary to 6.2 

6.3 : 
![capture](https://user-images.githubusercontent.com/24486147/52184507-5ad6e300-2814-11e9-965b-99c6c72751de.PNG)

6.2 : 
![capture2](https://user-images.githubusercontent.com/24486147/52184520-822db000-2814-11e9-8b86-41462aa659d0.PNG)

I use PaperSpigot 1.13.2.

**Comment by Esophose** [comment]
Verified. Looking into it now.

**Comment by Esophose** [comment]
The encoding of the file got screwed up. Use this lang file instead, you'll have to rename the extension from .txt to .lang. 
[fr_FR.txt](https://github.com/Esophose/PlayerParticles/files/2826246/fr_FR.txt)
