### ISSUE TITLE
Add effect with ID

### ISSUE THREAD

**Issue by Endothelium** [Esophose/PlayerParticles#18]
Hello, 

First off really nice plugin.

I need a feature for my server. I need to be able to add an effect by setting the id myself.

I am using a custom gui and for example i would have to set an effect for arrow at ID 2. Like this, if my player want to change the arrow effect for another, i know that arrows effect always have ID 2 and i can edit or remove the effect with ID 2, without removing other effect he already wear, like  a head effect on ID 1 for example.

Like this, its easier to manage for player, because they know they can for example have 1 effect for arrow,  1 trail, and 1 cloak.

The feature i request is mainly to prevent user to spam my gui and equip the same arrow effect like 3 times. If the player spam the button, it will only remove the effect at ID 2 and add it again.

Thanks

**Comment by Esophose** [comment]
You can use `/pp remove <effect | style>` to remove all particles with a given effect or style. This sounds like it would fit your use case. I don't see much benefit of allowing users to set the ID of particles.

Unless this is still a needed feature, I'll be closing this issue soon.
