### ISSUE TITLE
Admin command set player's effect,style

### ISSUE THREAD

**Issue by SaitDev** [Esophose/PlayerParticles#3]
Please add a admin command that can set player's effect and style.

Thanks for the cool plugin

**Comment by Esophose** [comment]
Coming in v4.6. No estimated release date.

**Comment by Esophose** [comment]
Pushed back to v5.2 - Working on getting out a final build for v5 that works with MC 1.8.

**Comment by Esophose** [comment]
Sorry, but this issue has been open for over a year now and I honestly don't see the need to implement this any time in the future.
