### ISSUE TITLE
Plugin annihilates test server console

### ISSUE THREAD

**Issue by Weasel-Beans** [Esophose/PlayerParticles#31]
Timings v2: https://timings.aikar.co/?id=fa03f19fb7c444ff8526dc573f7b4adb

This is for my local test server.

Console spam: https://pastebin.com/gU3c2Em8

Note that it's not possible to show every warning, as they are generated endlessly.

I was regenerating the config for this, so the old config was not in the server files on updating the plugin.

**Comment by Esophose** [comment]
This was fixed in v7.1. Please update to the latest version.

**Comment by Weasel-Beans** [comment]
There's a 7.1? I was downloading this from dev.bukkit.org, where's the new version?

**Comment by Esophose** [comment]
I can't recommend that you use dev bukkit to download plugins anymore. Spigot has way more up-to-date plugins on it and is where you can receive updates for PlayerParticles faster. You can find the Spigot page here: https://www.spigotmc.org/resources/playerparticles.40261

**Comment by Weasel-Beans** [comment]
Oh I see, thanks. I didn't know it was on Spigotmc

**Comment by Weasel-Beans** [comment]
Indeed it seems to fix the issue.
