### ISSUE TITLE
PP permissions

### ISSUE THREAD

**Issue by Alv5ro** [Esophose/PlayerParticles#38]
I found a bug where if you set a user with a rank (using LP) that allows them to have permissions to the pp, and the activite it. If you decide to demote them to a rank without it, their player particle doesn't get set to nothing, although they don't have access to the gui.

**Comment by Esophose** [comment]
This is intended due to a large amount of community feedback that wants to apply particles to players who don't have permission for the particles. If you want to forcefully clear the particles for players that no longer have access, use `/ppo <player> reset`

**Comment by Alv5ro** [comment]
Ok great, many thanks, the plugin works superbly!
