### ISSUE TITLE
Player's setting resetted when join

### ISSUE THREAD

**Issue by SaitDev** [Esophose/PlayerParticles#4]
Whenever i joined server, my effect and style be setted to none.
Using AuthmeReload for login security.
PlayerParticles latest release: 4.3

Updated: Found out why i lost effect. I'm OP so i have all permission to use paricles, but before joined by authme I'm not OP, authme temp remove my op permission.
Please add support for AuthmeReload. Thanks

**Comment by Esophose** [comment]
I don't see any added benefit for "login security". Minecraft already checks if an account is authenticated through their own servers, there is no need for server owners to do it themselves.
