### ISSUE TITLE
Feature Request: Permission for additional particles at once

### ISSUE THREAD

**Issue by RyanWoodruff** [Esophose/PlayerParticles#42]
**Feature Request Details:**

Have a permission such that users with this permission can have that many active particles on at once, overriding the config. Currently all that is available is "unlimited" - which wouldn't be good and cause lag.

**Example:**

**playerparticles.particles.num** will allow a user with this permission to use num amount of particles at once.

This would be useful for donation rewards etc, allowing user to have more active particles up to their at once if they so wish.

**Alternative method**

Have it in the config instead of permissions. i.e

Default: 1
Donator: 2
VIP: 3
MVP: 4

would allow each rank have that amount of particles active at once.

Thanks.

**Comment by RyanWoodruff** [comment]
Perhaps the same thing with groups and fixed particles aswell.

**Comment by Esophose** [comment]
Added, will be in v7.10
