### ISSUE TITLE
Feature Request: Ability to have worldguard regions as a flag to disable particles

### ISSUE THREAD

**Issue by Firosee** [Esophose/PlayerParticles#43]
Really would like to have an option to disable particles using worldguard regions, and not just worlds as i have my warzone connected to my spawn, and would like to allow people to use them in spawn, but not in the warzone!

Thanks!

**Comment by Firosee** [comment]
@Esophose Any updates regarding this?

**Comment by Esophose** [comment]
This at the very least will not be added in v7.10 due to there being multiple WorldGuard versions that I have to support. It will take a bit longer for me to get it added as well since I know basically nothing about WorldGuard.

**Comment by Esophose** [comment]
@Firosee This has been implemented and will be available in the v7.12 release. You can find a dev build here: https://ci.codemc.io/job/Esophose/job/PlayerParticles/32/
