### ISSUE TITLE
Feature Request: Ability to add a lore to this item in the gui

### ISSUE THREAD

**Issue by Firosee** [Esophose/PlayerParticles#44]
As per this image (https://gyazo.com/f962eae4d4c909e2a09a7bae2d01dde7) i have added where i would like to have an option to add a custom lore, as i am using the preset group feature as a community based thing, where people can share their favorite particle groups, and i would like to be able to show who it was made by to credit them.

Thanks!

**Comment by Firosee** [comment]
@Esophose Any updates regarding this?

**Comment by Esophose** [comment]
This won't be added until I get to reworking the GUI entirely. It needs a lot of work, and it seems super obscure to only add the lore feature to this one spot.

**Comment by Firosee** [comment]
It is very crutial for a feature on my server, you cant even do a temp build for me until its added pls??

**Comment by Esophose** [comment]
This is a free plugin, and my time is being used up because it is finals week at school. I don't have the time to do this right now.

**Comment by Oribuin** [comment]
An alternative would be using a plugin such as DeluxeMenus and manually creating all the effects until this feature is added.

**Comment by Firosee** [comment]
Deluxemenus is not capable of doing that. The GUI for PlayerParticles is not able to be re-created in deluxemenus.

**Comment by Firosee** [comment]
Im just going to pay my developer to add it, as lets be honest, it is never going to be added.

**Comment by Oribuin** [comment]
DeluxeMenus is absolutely capable of doing that, Create all the presents manually and just use commands to apply them?

It doesn't require much brainpower to figure that one out.

**Comment by Firosee** [comment]
If you have a look at the screenshot i sent, i dont want to add a lore to the main gui item, i want to add a lore to the preset particles. I am unable to get what is currently shown in a deluxemenus menu. If you seem to think you can, give it a go and send it to me, as im pretty sure its not possible to re-recreate the whole gui, in deluxemenus.

**Comment by Oribuin** [comment]
Uh, Look at that gif? I recreated the entire menu in DeluxeMenus, Can it automatically create all the presets, No but for the third time you can manually input all the presets.

**Comment by Firosee** [comment]
This is closed because i paid my dev to add it himself, so would you please stop replying here? Thanks.
