### ISSUE TITLE
Custom .lang file

### ISSUE THREAD

**Issue by thapowah** [Esophose/PlayerParticles#45]
Is there anyway I can add my own .lang file?

**Comment by Esophose** [comment]
If you mean to create one for your own server, just copy one of the existing files in the locale folder and rename it, then use that name in the config.yml.

If you mean to create one in the plugin's source code, copy one of the existing locale files, edit it, then add it to the `reload()` method in the LocaleManager.

**Comment by thapowah** [comment]
This is the error I get when I copy a lang file and edit it
https://gyazo.com/c6478b6a97a367d358d4945ae3fd8cf8

**Comment by Esophose** [comment]
I am having no issues with this. I copied the en_US.lang file and named it test.lang. I then opened the config.yml, set locale to test, and it loaded all of my changes correctly. Please make sure you are following the steps that I just provided.
