### ISSUE TITLE
Fishing Style Applies to all players

### ISSUE THREAD

**Issue by Ashinos** [Esophose/PlayerParticles#46]
When someone is using the Fishing Style, any user who fishes will have the same particle effect as the user using it applied even if they do not have permission to the style.

Using the latest version of the plugin and paper 1.15.2

**Comment by Esophose** [comment]
Looked at the code and confirmed the issue. I will have it fixed in the next update, thanks for reporting.

**Comment by Esophose** [comment]
Fixed, will be released in v7.10
