### ISSUE TITLE
Option to use anvil renaming GUI for saving group

### ISSUE THREAD

**Issue by MegaNarwhal** [Esophose/PlayerParticles#49]
My server uses Bungeecord with chat shared between all servers, and as a result chat never reaches the individual servers. This makes it impossible to save a particle group from the GUI and it must be done via command instead. Adding an option to use the anvil GUI to specify the name of the particle group would solve this. Alternatively, an option to remove the GUI option to save would at least prevent players from entering the naming dialog for servers where it cannot be used.

**Comment by Esophose** [comment]
A setting to circumvent entering a message in chat for bungee has been added and will be in the v7.17 release. It doesn't use the anvil GUI as you wanted, but it should be good enough for your needs.
