### ISSUE TITLE
Permission check on login

### ISSUE THREAD

**Issue by Esophose** [Esophose/PlayerParticles#53]
A configuration option called check-perms-on-login.
If this is enabled, then on login, PP will check if the player has permission to use the particles that they have active. It will remove the particles which they do not have permission for. If this is disabled which is how it currently acts, then players will keep their active particles, even if they do not have permission.

Setting should be disabled by default.

**Comment by xsmeths** [comment]
This would be epic.

**Comment by Esophose** [comment]
Added in 668191202d398068ee4b00d403cf1540598b2384
