### ISSUE TITLE
Particles still visible in vanish

### ISSUE THREAD

**Issue by HexedHero** [Esophose/PlayerParticles#58]
PlayerParticles version 7.15
SuperVanish version 6.2.0
ProtocolLib version 4.6.0-SNAPSHOT-b480

Going into /vanish will not stop your particles from showing.

Video: https://cdn.hexedhero.com/u/7vDBWZ9UlF.mp4

**Comment by Esophose** [comment]
This is currently the intended functionality. When you vanish, everyone _except for you_ don't be able to see your particles. Would it be more desirable to have your particles hide even to yourself when vanished?
