### ISSUE TITLE
Disable messages with empty ''

### ISSUE THREAD

**Issue by ItsMennyo** [Esophose/PlayerParticles#6]
Hey,

I wonder if you can add when you set a message to '' (so no text) that it will not be displayed at all instead of an error?

Tnxx anyway!

**Comment by Esophose** [comment]
Coming soon :)
Honestly have no idea why I didn't do this in the first place. Not all messages will be able to be set to nothing, but most of them will be.

**Comment by ItsMennyo** [comment]
Yay!

Yeah, sometimes it dysplays 2 messages but I just want to hide some commands but then you see 2 times a message with no access in my case 😜

**Comment by Esophose** [comment]
All done and pushed a release to Bukkit/Spigot. Enjoy :)
