### ISSUE TITLE
Effect/Style settings not applying from pp reload, swords style missing Netherite Sword

### ISSUE THREAD

**Issue by JasonHorkles** [Esophose/PlayerParticles#63]
When I modify or disable styles, it doesn't seem to apply in the GUI even after doing `/pp reload`
Paper-300 1.16.4
PP 7.16

**Comment by Esophose** [comment]
I could have sworn I fixed that, I guess it never got committed. I'll have it fixed in the next update, sorry for any inconvenience.

**Comment by JasonHorkles** [comment]
It does seem to work after a restart still but yeah the reload doesn't work
Thanks for the fast reply!

**Comment by JasonHorkles** [comment]
Also idk if you want me to make a new issue for this or not but Netherite Swords should probably be added to the default Swords style, unless you didn't include it by default for compatibility reasons

**Comment by Esophose** [comment]
Now that one I didn't know about, nice catch.

**Comment by Esophose** [comment]
Issues resolved, you can find the dev build with the patch and a couple others here: https://ci.codemc.io/job/Esophose/job/PlayerParticles/46/
