### ISSUE TITLE
Correct permission for preset groups?

### ISSUE THREAD

**Issue by vcp5k** [Esophose/PlayerParticles#68]
Hi there!
I'm having issues with setting up the permissions for my preset groups, since I can't find a specific permission for them.
Should players have access to the styles and effects involved in those presets beforehand or can I just give the preset to a certain rank without giving the effect?
Please let me know what I'm not doing right.

Best regards,
vcp5k

**Comment by Esophose** [comment]
Giving them access to all effects and styles in the group will allow them to use the group, yes. There's another way to allow them to use it without having permission though. If you set allow-permission-override on the preset group you want and give it a permission, giving a player that permission will allow them to use the group regardless of what effects and styles they have access to.
