### ISSUE TITLE
PP Reload causes TPS to drop.

### ISSUE THREAD

**Issue by mibby** [Esophose/PlayerParticles#69]
PlayerParticles dev 51
https://ci.codemc.io/job/Esophose/job/PlayerParticles/

Reloading PlayerParticles with ``/pp reload`` causes TPS to take a massive hit. Main thread freezing (tps dropping to ~10-15) until it's done reloading / initializing (every single time you try). Caused by establishing database connection?

```
[04:37:06] [Server thread/INFO]: mibby issued server command: /pp reload
[04:37:06] [Server thread/INFO]: [PlayerParticles] Data handler connected using MySQL.
[04:37:09] [Server thread/INFO]: [PlayerParticles] Reloaded configuration.
```

Config
https://paste.gg/p/anonymous/40e0aa9b7143441ca9f4777a4ca1bb46/files/ba58cf3b174b4b3ca2c18136833fde94/raw

**Comment by Esophose** [comment]
This should be resolved in dev build 52. I was reluctant to do it because of the potential desyncs that can happen, but the only one that happened (that I noticed) was easily resolvable. If you could test this to make sure it works with your database connection that would be great. https://ci.codemc.io/job/Esophose/job/PlayerParticles/52/

**Comment by mibby** [comment]
It's a little better but there's still a bit of a performance hit when reloading (drop to ~16-17 tps) and takes about 2 seconds to finish initializing. It must be getting hung up on something.

```
[02:25:30] [Server thread/INFO]: mibby issued server command: /pp reload
[02:25:30] [Craft Scheduler Thread - 153 - PlayerParticles/INFO]: [PlayerParticles] Data handler connected using MySQL.
[02:25:32] [Craft Scheduler Thread - 130 - PlayerParticles/INFO]: [PlayerParticles] Reloaded configuration.
[02:25:45] [Server thread/INFO]: mibby issued server command: /pp reload
[02:25:45] [Craft Scheduler Thread - 132 - PlayerParticles/INFO]: [PlayerParticles] Data handler connected using MySQL.
[02:25:47] [Craft Scheduler Thread - 146 - PlayerParticles/INFO]: [PlayerParticles] Reloaded configuration.
```

**Comment by Esophose** [comment]
The message simply prints out 10 ticks after the reload command is run. https://prnt.sc/ytve0t

**Comment by mibby** [comment]
Is there any way for me to expose that debug timer when reloading or is that a custom debug build? It really feels like it takes longer than 21ms and dropping performance down to 16 tps until it completes is not ideal. Reloading more gracefully would be preferred. 

Other SQL database plugins I use and reload don't impact performance.

**Comment by Esophose** [comment]
I just temporarily added the message there. Here's a build with it
[playerparticles-7.19-reload-stats.zip](https://github.com/Esophose/PlayerParticles/files/5951412/playerparticles-7.19-reload-stats.zip)

**Comment by mibby** [comment]
How weird. The reload claims to only take 15-17ms. The TPS drop starts to happen _after_ that output. Running a timings check, it seems to be caused by PlayerParticle's PermissionManager.

![link](https://i.imgur.com/y8CThem.png)
https://timings.aikar.co/?id=b75995ae870e4411b9f52c3a1e97b5cf

**Comment by Esophose** [comment]
Can you run a spark profiler report just for that reload command? I'm not exactly sure what's causing that to happen as permission checks are usually supposed to be really fast. The plugin is called spark on Spigot and you can run the profiler with `/spark profiler --timeout 30` and run the reload command right after that, it'll tell me exactly what's causing the slowdown

**Comment by mibby** [comment]
Sure, I'm aware of Spark (WarmRoast replacement). Give me a couple minutes.

**Comment by mibby** [comment]
Here's a single ``/pp reload`` at the beginning of a 30 second spark profile.
https://spark.lucko.me/#SVb0llT9WL

**Comment by Esophose** [comment]
Looks like it was taking a long time to register all the permissions, here's a build with that removed so it's only done on startup now https://ci.codemc.io/job/Esophose/job/PlayerParticles/55/

**Comment by mibby** [comment]
Fix seems to be working great, thanks! No more major tps hit when reloading PP.
