### ISSUE TITLE
Is it possible to create custom colored particles such as red redstone dust?

### ISSUE THREAD

**Issue by mibby** [Esophose/PlayerParticles#7]
Coming from TrailGUI (https://github.com/JamieSinn/TrailGUI), I didn't seem to find any rainbow redstone (coloredreddust) or red redstone trail in PlayerParticles. Is it possible to create custom particles such as ones that exist within TrailGUI that don't in PP?

Also no town aura or endersignal effect from what I can tell.

**Comment by Esophose** [comment]
PlayerParticles allows you to customize certain particle effects with something that I called 'data'. This can be edited by using the command /pp data. By using the command with no arguments, it will tell you what kind of data your current particle effect uses and how to apply it. For instance, if your current effect is reddust and you use '/pp data 255 0 0' you will get red. You can also use '/pp data rainbow' to get a magical rainbow effect.
The effects 'depthsuspend' and 'townaura' both do the exact same thing, so I decided to remove townaura. Use /pp effect depthsuspend to get the same effect. 
The endersignal effect isn't actually a single particle, but a mixture of two, 'portal' and 'iconcrack' with the enderpearl data. There isn't currently a way to replicate this, but you can customize the data for iconcrack to look like the eye of ender if you want. 
I hope this helps :)
