### ISSUE TITLE
Add PP Toggle status to the PlayerParticles GUI

### ISSUE THREAD

**Issue by mibby** [Esophose/PlayerParticles#71]
Had a user complain about particles not displaying for months and couldn't figure out why. Spent hours debugging going through reinstalls, toggling all settings, permissions etc. etc.. Apparently he toggled PlayerParticles with ``/pp toggle`` many months ago and forgot about it. ``/pp reset`` did not reset the disabled status and the ``/pp`` gui does not indicate the current toggle state anywhere. 

Would it be possible to add a toggle button to the GUI or show the toggle state in the lore when hovering over your player head? Could also make clicking on the head toggle the state. This way the command isn't buried and forgotten about in the help menu when players are use to GUI setting only.

**Comment by Esophose** [comment]
As you wish https://ci.codemc.io/job/Esophose/job/PlayerParticles/53/

**Comment by mibby** [comment]
Thanks for adding this, it works great. Hopefully will lead to less people complaining about particles not working due to user error!
