### ISSUE TITLE
Particle style Arrows causes memory leak

### ISSUE THREAD

**Issue by Xayanix** [Esophose/PlayerParticles#73]
![image](https://user-images.githubusercontent.com/12672902/109737315-1cb07700-7bc6-11eb-813d-b2de4fed6d73.png)

**Comment by Esophose** [comment]
I don't see how it could be possible for it to cause a memory leak, there are 3 different checks to make sure that the arrows are getting removed from the array https://github.com/Esophose/PlayerParticles/blob/master/src/main/java/dev/esophose/playerparticles/styles/ParticleStyleArrows.java#L37

**Comment by Xayanix** [comment]
Well, im using latest version and it consumes ~1.5G of memory.

**Comment by HexedHero** [comment]
Unable to reproduce this in any way, spawning 5 arrows per tick for 10+ mins in loaded and unloaded chunks with instantly high config settings to make PP track all my arrows.

**Comment by Esophose** [comment]
Closing as unable to reproduce
