### ISSUE TITLE
Add API Method for providing Dust Color

### ISSUE THREAD

**Issue by thisisfel1x** [Esophose/PlayerParticles#78]
After looking into the API, I couldn't find any way to assign a rgb value to a dust particle effect.

Example: 
`PlayerParticlesAPI.getInstance().addActivePlayerParticle(player, ParticleEffect.DUST, ParticleStyle.fromName("halo"));`
[Result](https://imgur.com/a/e0uAHt6)

Solution:
Something like `PlayerParticlesAPI.getInstance().addActivePlayerParticle(player, ParticleEffect.DUST, ParticleStyle.fromName("halo"), OrdinaryColor.fromRGB(...)` would be great

Would be great to see this in the API!
Best regards

**Comment by Esophose** [comment]
Eh? `new OrdinaryColor(r, g, b)` Did you want one that took an rgb value itself? In that case you can do Color.fromRGB(rgb) and get the individual r, b, and b values from that.

**Comment by Esophose** [comment]
In addition to that, you can get the styles from `DefaultStyles.DUST` instead of looking them up by name

**Comment by HexedHero** [comment]
Doing
`PlayerParticlesAPI.getInstance().addActivePlayerParticle(event.getPlayer(), ParticleEffect.DUST, ParticleStyle.fromName("halo"), new OrdinaryColor(97, 33, 37));`
works for me.

**Comment by thisisfel1x** [comment]
Sorry guys, I'm dump. Just checked `OrdinaryColor.SOMETHING` and not `new OrdinaryColor(...)`
Solved, thanks for your help :)
